name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::python=3.10
  - conda-forge::pandas=2.2.1
  - conda-forge::requests=2.31.0
  - conda-forge::pip=23.3.1
  - conda-forge::hydra-core=1.3.2
  - conda-forge::mlflow=2.8.1
  - conda-forge::scikit-learn=1.4.1
  - conda-forge::matplotlib=3.8.3
  - conda-forge::plotly=5.19.0
  - conda-forge::pillow=10.2.0
  - conda-forge::pytest=8.0.2
  - conda-forge::scipy=1.12.0
  - conda-forge::pyyaml=6.0.1
  - pip:
      - wandb==0.16.4
      - omegaconf==2.3.0
      - databricks-cli==0.18.0
